#!/bin/bash

STOW_FOLDERS=("tmux" "bin" "bat" "zsh" "git" "starship" "yazi" "ghostty")

for item in "${STOW_FOLDERS[@]}"; do
    echo "- stow $item -t $HOME"
    stow -D $item -t $HOME
    stow $item -t $HOME
done
