#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,bin,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/personal/chaCon/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install_test
