#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,bin,git,i3,picom,tmux,xorg,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.chaConfig/arch/dotfiles
fi

cd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow -D $folder -t $HOME"
    stow -D $folder -t $HOME
done
