#!/bin/bash
script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"

cd $script_dir
scripts="$(find scripts -mindepth 1 -maxdepth 1 -type f | sort)"

echo "*-*   *-*   *POW!*   *-*   *-*"
actions=("BANG!" "ZAP!" "CRASH!" "POOF!" "BAM!")
length=${#actions[@]}

count=0
for script in $scripts; do
  echo "   *   ${actions[$((count % length))]}   *   "
  echo "running script: $script"
  ./$script
  ((count++))
  echo " ---   ---   ---   ---   ---   ---"
done
