#!/bin/bash
script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
os="$(uname)"
dry="0"
container="0"

cd $script_dir
scripts="$(find scripts -mindepth 1 -maxdepth 1 -type f | sort)"

while [[ $# > 0 ]]; do
    case "$1" in
        --dry) 
            dry="1"
            shift
            ;;
        --os)
            os="$2"
            shift 2
            ;;
        --container)
            container="1"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "*-*   *-*   *POW!*   *-*   *-*"
actions=("BANG!" "ZAP!" "CRASH!" "POOF!" "BAM!")
length=${#actions[@]}

count=0
for script in $scripts; do
    log "   *   ${actions[$((count % length))]}   *   "
    log "running script: $script"
    execute ./$script $os $container
    ((count++))
    log " ---   ---   ---   ---   ---   ---"
done
