#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,bin,zsh,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.chaConfing/iOS/dotfiles
fi

cd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow -D $folder -t $HOME"
    stow -D $folder -t $HOME
done
