#!/bin/bash

echo "Creating base folders"
mkdir -p $HOME/workspace/work $HOME/workspace/personal $HOME/workspace/github.com/chaCon $HOME/workspace/projects

echo "Cheking for ssh key"
if ls $HOME/.ssh | grep -q "chacon"; then
    echo "- SSH key found at: $HOME/.ssh/chacon"
    echo "- Add the key to GitHub. Have you done it? (y/n)"
    read answer
else
    echo "- Creating SSH key ED25519"
    ssh-keygen -t ed25519 -C "montt.octavio@gmail.com" -f $HOME/.ssh/chacon -N ""
    echo "- Add the key to GitHub. Have you done it? (y/n)"
    read answer
fi

# TODO: PROPAGETE THE EXIT
# if [[ $answer != 'y' ]]; then
#     echo "- Go and added it!!"
#     exit 1
# fi

echo "Cheking for git folders"
if [[ ! -d "$HOME/workspace/notes" ]];then
    git clone git@github.com:L-chaCon/notes.git $HOME/workspace/notes
fi
if [[ ! -d "$HOME/Documents/personal" ]];then
    git clone git@github.com:L-chaCon/Documents.git $HOME/Documents/personal
fi
# if [[ ! -d "$HOME/Pictures/personal" ]];then
#     git clone git@github.com:L-chaCon/Images.git $HOME/Pictures/personal
# fi

# NOTE: iOS
if [[ $1 = "iOS" ]]; then
    echo "Checking Homebrew"
    if ! command -v brew &>/dev/null; then
        echo "- Homebrew is not installed. Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        export PATH=/usr/local/bin:$PATH >> $HOME/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)" >> $HOME/.zprofile
        source $HOME/.zprofile
    else
        echo "- Homebrew is already installed."
    fi
    brew update && brew upgrade && brew cleanup
    brew install tree sshs tldr ripgrep

    echo "Checking for JetBrains font"
    if ls $HOME/Library/Fonts | grep -q JetBrainsMonoNLNerdFont; then
        echo "- Installing JetBrais Nerd Font..."
        brew install --cask font-jetbrains-mono-nerd-font
    else
        echo "- JetBrais Nerd Font already installed."
    fi

    
    # TODO: HACER UN SCRIPT PARA USAR `tldr` funciona tldr -C (lo que busco) | bat

    echo "Checking wezterm"
    if ! command -v wezterm &>/dev/null; then
        echo "- WezTerm is not installed. Installing WezTerm..."
        brew install --cask wezterm@nightly
    else
        echo "- WezTerm is already installed."
        brew upgrade --cask wezterm@nightly --no-quarantine --greedy-latest
    fi

# NOTE: Ubuntu
elif [[ $1 == "ubuntu" ]]; then
    echo "ubuntu"
# NOTE: Debian
elif [[ $1 == "debian" ]]; then
    echo "debian"
fi
