#!/bin/bash

echo "Checking ZSH"
if ! command -v zsh &>/dev/null; then
  echo "- ZSH is not installed. Installing ZSH..."
  brew install zsh
else
  echo "- ZSH is already installed."
fi

echo "Installing command line tools"
brew install fzf fd bat git-delta lsd starship zoxide pyenv pyenv-virtualenv

echo "Checking Oh My Zsh"
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  echo "- Oh My Zsh is not installed. Installing Oh My Zsh..."
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
  echo "- Oh My Zsh is already installed."
fi

echo "Checking Zsh Auto Suggestions"
if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]]; then
  echo "- Auto Suggestion is not installed. Installing Auto Suggestions..."
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
else
  echo "- Auto Suggestion is already installed."
fi

echo "Checking Zsh Syntax Highlighting"
if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]]; then
  echo "- Syntax Highlighting is not installed. Installing Syntax Highlighting..."
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
else
  echo "- Syntax Highlighting is already installed."
fi

echo "Checking Git fzf"
if [[ ! -d "$HOME/.fzf-git.sh" ]]; then
  echo "- Git fzf is not installed. Installing Git fzf..."
  git clone https://github.com/junegunn/fzf-git.sh.git $HOME/.fzf-git.sh
else
  echo "- Git fzf is already installed."
fi
