#!/bin/bash
OS=$1
CONTAINER=$2

if [[ $CONTAINER == "0" ]]; then
    if [[ $OS == "Darwin" ]]; then
        echo "Cheking NeoVim"
        if [[ ! -d $HOME/.local/neovim ]]; then
            echo "- Neovim is not installed. Installing Neovim..."
            current_path=$(pwd)
            git clone git@github.com:neovim/neovim.git $HOME/.local/neovim
            cd $HOME/.local/neovim
            git fetch
            xcode-select --install
            brew install ninja cmake gettext curl luajit pyright
            rm -r build/
            make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=$HOME/.local/nvim"
            make install
            cd $current_path
        else
            echo "- Neovim is already installed."
        fi

        echo "Checking Nvim Configuration"
        if [[ ! -d $HOME/.config/nvim ]];then
            echo "- Config is not installed. Installing Config..."
            mkdir -p $HOME/.config
            git clone git@github.com:L-chaCon/chaCon.nvim.git $HOME/.config/nvim
        else
            echo "- Config is already installed."
        fi


elif [[ $2 == "1" ]]; then
    echo "HOLO"
else 
    echo "uknown opton: $2"
fi
