#!/bin/bash
OS=$1

if [[ $OS = "Darwin" ]]; then
  if ! command -v aerospace &>/dev/null; then
    echo "- Aerospace is not installed. Installing Aerospace..."
    brew install --cask nikitabobko/tap/aerospace
    defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
  else
    echo "- Aerospace is already installed."
  fi
fi
