#!/bin/bash

STOW_FOLDERS=("tmux" "bin" "zsh" "git" "starship" "wezterm" "yazi")

# NOTE: iOS
if [[ $1 = "iOS" ]]; then
    if ! command -v stow &>/dev/null;then
        echo "- Stow is not installed. Installing Stow..."
        brew install stow
    else
        echo "- Stow is already installed."
    fi

    current_folder=$(pwd)
    rm -rf $HOME/.zshrc

    echo "Creating links to dotfiles"
    cd dotfiles
    for item in "${STOW_FOLDERS[@]}"; do
        echo "- stow $item -t $HOME"
        stow -D $item -t $HOME
        stow $item -t $HOME
    done
    cd $current_folder


# NOTE: Ubuntu
elif [[ $1 == "ubuntu" ]]; then
    echo "ubuntu"
# NOTE: Debian
elif [[ $1 == "debian" ]]; then
    echo "debian"
fi
